services:
  # schedule service db connection
  db-schedule:
    image: postgres:17
    container_name: db-schedule
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schedule/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  # schedule service
  schedule-service:
    build: ./schedule
    container_name: schedule-service
    ports:
      - "8080:8080"
    depends_on:
      - db-schedule
      - rabbitmq
    environment:
      DB_USER: postgres
      DB_PASS: postgres
  # rabbitmq service
  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 512m
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  # notification service db connection
  db-notification:
    image: postgres:17
    container_name: db-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
  # notification service
  notification-service:
    build: ./notification
    container_name: notification-service
    ports:
      - "8082:8081"
    depends_on:
      - db-notification
      - rabbitmq
    environment:
      MAIL_USER: <insert_here_your_app_email>
      MAIL_PASSWORD: <insert_here_your_app_email_password>